### ISSUE TITLE
BlockRegen Error:

### ISSUE THREAD

**Issue by InsideIntel** [Aurorion/BlockRegen#5]
[23:32:56 WARN]: [BlockRegen] Task #80490 for BlockRegen v3.4.0 generated an exception
 [23:32:56 WARN]: [BlockRegen] Task #80490 for BlockRegen v3.4.0 generated an exception
java.lang.NullPointerException: null
at nl.Aurorion.BlockRegen.Events.BlockBreak$2.run(BlockBreak.java:397) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-626]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-626]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-626]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-626]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-626]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-626]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by JackScurvy** [comment]
I'm getting the same issue.
